feat: Add postInitScript and platform fields in template.config.js fo…
callstack/react-native-visionos pull request #146
Opened 2024-05-29 12:40 UTC by Piotrfj

…r react-native add-platform compatibility

## Summary:
The motivation for this change is to add support for react-native add-platform command

## Changelog:

- Added platforms and postInitScript in template.config.js
- Created postInitScript.js file

## Test Plan:

See if steps presented in https://github.com/react-native-community/cli/pull/2298 are working the same.

2024-05-29 12:46 UTC, szymonrybczak requested changes

2024-05-29 12:46 UTC, szymonrybczak commented on packages/react-native/postInitScript.js
> +  const relativeXcodeProjectPath = `visionos/${projectName}.xcworkspace`;
Are you sure this path will exist?

We cannot assume this path because Cocoapods are not installed 😅

2024-05-29 12:46 UTC, szymonrybczak commented on packages/react-native/postInitScript.js
> +  const instructions = `
Please align instructions with the information about installing Cocoapods.

2024-06-04 17:38 UTC, szymonrybczak commented on packages/react-native/postInitScript.js
> +    • cd "${projectDir}/ios"
```suggestion
    • cd "${projectDir}/visionos"
```

2024-06-24 09:53 UTC, okwasniewski commented
Hey, 

@Piotrfj can you rebase your branch? You can also create a cherry-pick of you commits to the rebased main. Sorry for the inconvenience

2024-07-15 09:31 UTC, closed without merging